In [ ]:
pip install numpy

In [ ]:
import numpy as np

Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
A = np.array([
     [1, 2, 3, 3, 1],
     [6, 8, 11, 10, 7]
])
print(A)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [ ]:
mean_a = np.mean(A, axis = 0,dtype=float)
print(mean_a)

[3.5 5.  7.  6.5 4. ]


Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [ ]:
a_centered = A - mean_a
a_centered

array([[-2.5, -3. , -4. , -3.5, -3. ],
       [ 2.5,  3. ,  4. ,  3.5,  3. ]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
a1 = a_centered[:, 0]
a2 = a_centered[:, 1]
a_centered_sp = np.dot(a1, a2)
a_centered_sp

15.0

In [ ]:
n = A.shape[0]
n

2

In [ ]:
n_new = a_centered_sp / (n - 1)
n_new

15.0

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [ ]:
np.cov(A, rowvar=False)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

Не совсем понимаю связи, возможно я что-то неправильно сделал в первой части

Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [ ]:
pip install pandas

In [ ]:
import pandas as pd

In [ ]:
a = {
    'author_id' : [1,2,3],
    'author_name' : ['Тургенев', 'Чехов', 'Островский']
}
b = {
    'author_id' : [1, 1, 1, 2, 2, 3, 3],
    'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price' : [450, 300, 350, 500, 450, 370, 290]
}

authors = pd.DataFrame(a)
book = pd.DataFrame(b)

In [ ]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [ ]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [ ]:
authors_price = pd.merge(authors, book, on = 'author_id', how='outer')
authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [ ]:
top = authors_price.sort_values(by='price', ascending=False)
top

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [ ]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
500                500        500  500.000000
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000